analog:
- dpu: DPU3013
  device: 30HAG21AA
  cmd: HW.AQ010101.PV
  fb: HW.AI010502.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: 启动系统暖管出口电动调整门指令
- dpu: DPU3013
  device: 30HAG20AA
  cmd: HW.AQ010103.PV
  fb: HW.AI010501.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: 炉水泵出口电动调整门指令
- dpu: DPU3013
  device: 30LCQ91AA
  cmd: HW.AQ010104.PV
  fb: HW.AI010503.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: 机组排水槽减温水气动调整门指令
- dpu: DPU3013
  device: 30LCL83AA
  cmd: HW.AQ010105.PV
  fb: HW.AI010504.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: 启动疏水泵再循环电动调整门指令
- dpu: DPU3013
  device: 30LCL84AA
  cmd: HW.AQ010106.PV
  fb: HW.AI010505.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: 启动疏水泵出口母管电动调整门指令
- dpu: DPU3013
  device: 30HJF50AA
  cmd: HW.AQ030102.PV
  fb: HW.AI030301.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: 燃油回油调节阀指令
- dpu: DPU3013
  device: 30LAB70AA
  cmd: HW.AQ020304.PV
  fb: HW.AI020401.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: 主给水电动隔离门指令
- dpu: DPU3013
  device: 31HLA30AA
  cmd: HW.AQ070101.PV
  fb: HW.AI080607.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: A送风机热风再循环风门指令
- dpu: DPU3013
  device: 30HFE32AA
  cmd: HW.AQ070103.PV
  fb: HW.AI090403.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: A磨暖风器出口电动调节风门指令
- dpu: DPU3013
  device: 32HLA30AA
  cmd: HW.AQ080301.PV
  fb: HW.AI090307.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: B送风机热风再循环风门指令
- dpu: DPU3016
  device: 31HLB10AA
  cmd: HW.AQ120401.PV
  fb: HW.AI120602.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: A一次风机动叶指令
- dpu: DPU3016
  device: 31HLB20AA
  cmd: HW.AQ110201.PV
  fb: HW.AI110401.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: A送风机动叶指令
- dpu: DPU3016
  device: 31HNC20AA
  cmd: HW.AQ090201.PV
  fb: HW.AI090502.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: A引风机动叶指令
- dpu: DPU3017
  device: 32HLB20AA
  cmd: HW.AQ050101.PV
  fb: HW.AI050201.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: B送风机动叶指令
- dpu: DPU3017
  device: 32HNC20AA
  cmd: HW.AQ030201.PV
  fb: HW.AI030402.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: B引风机动叶指令
- dpu: DPU3017
  device: 32HLB10AA
  cmd: HW.AQ060601.PV
  fb: HW.AI060702.PV
  template: analog
  transform:
    type: inertia
    T: 2.0
  online_writable: true
  desc: B一次风机动叶指令
