variables:
- tag: MW
  name: 机组实发功率
  type: AI
  unit: MW
  description: 机组有功功率
  opc_node: DPU3013.HW.AI010605.PV
- tag: MWtest
  name: ''
  type: CALC
  unit: ''
  opc_node: ''
  description: ''
- tag: unit_power
  name: 发电机功率1
  type: AO
  unit: MW
  opc_node: DPU3013.HW.AI010605.PV
  description: 发电机功率1
- tag: TESTOUT
  name: TESTOUT
  type: CALC
  unit: ''
  description: 画布变量（自动同步）
- tag: CEHSI
  name: CEHSI
  type: CALC
  unit: ''
  description: 画布变量（自动同步）
- tag: generator_power
  name: 发电机有功功率
  type: AI
  unit: MW
  opc_node: DPU3013.SH0021.PROMW.IN
  description: 发电机有功功率
- tag: main_steam_pressure
  name: 主蒸汽压力1
  type: AO
  unit: MPa
  opc_node: DPU3013.HW.AI010601.PV
  description: 主蒸汽压力1
- tag: main_steam_pressure_2
  name: 主蒸汽压力2
  type: AO
  unit: MPa
  opc_node: DPU3013.HW.AI020402.PV
  description: 主蒸汽压力2
- tag: unit_power_2
  name: 发电机功率2
  type: AO
  unit: MW
  opc_node: DPU3013.HW.AI020405.PV
  description: 发电机功率2
- tag: main_steam_pressure_3
  name: 主蒸汽压力3
  type: AO
  unit: MPa
  opc_node: DPU3013.HW.AI020501.PV
  description: 主蒸汽压力3
- tag: unit_power_3
  name: 发电机功率3
  type: AO
  unit: MW
  opc_node: DPU3013.HW.AI030306.PV
  description: 发电机功率3
- tag: coal_flow
  name: 经过BTU修正后煤量
  type: AI
  unit: t/h
  opc_node: DPU3013.SH0098.PROFCF.IN
  description: 经过BTU修正后煤量
- tag: ccs_load_setpoint_1
  name: 协调控制负荷设定#1
  type: AI
  unit: MW
  opc_node: DPU3013.SH0150.AOUT37410.PV
  description: 协调控制负荷设定#1
- tag: ccs_load_setpoint_2
  name: 协调控制负荷设定#2
  type: AI
  unit: MW
  opc_node: DPU3013.SH0150.AOUT04429.PV
  description: 协调控制负荷设定#2
- tag: ccs_load_setpoint_3
  name: 协调控制负荷设定#3
  type: AI
  unit: MW
  opc_node: DPU3013.SH0150.AOUT76009.PV
  description: 协调控制负荷设定#3
- tag: steam_pressure_feedback
  name: 主蒸汽压力
  type: AI
  unit: MPa
  opc_node: DPU3013.SH0031.PRO1.IN
  description: 主蒸汽压力
